// view所需要的公共字段
const viewCommon = {
  viewId: 'view.id',
  viewType: 'view.type',
  viewSubType: 'view.sub.type',
  viewReferrer: 'view.referrer',
  viewUrl: 'view.url',
  viewHost: 'view.host',
  viewPath: 'view.path',
  viewName: 'view.name',
  viewPageTitle: 'view.page.title',
  viewPathGroup: 'view.path.group',
  viewQuery: 'view.url.query',
  viewUserAgent: 'view.userAgent',
  viewEventType: 'view.eventType', //view页面事件类型
  viewStartTime: 'view.startTime', // 页面的开始时间
  viewEndTime: 'view.endTime', // 页面的结束时间
};

//scope
const scopeCommon = {
  extra: 'scope.extra',
};

// 用户信息所需要的公共字段
const userCommon = {
  isSign: 'user.isSignIn',
  userId: 'user.id',
  userEmail: 'user.email',
};

// session信息所需要的公共字段
const sessionCommon = {
  sessionStartTime: 'session.start.time',
  sessionId: 'session.id',
  sessionType: 'session.type',
};

// action信息所需要的公共字段
const actionCommon = {
  actionId: 'action.id',
};

// 所有采集字段所需要的别名
const aliasName = {
  base: {
    appId: 'app.identifier',
    name: 'app.name',
    projectName: 'web.groupName',
    projectVersion: 'web.groupVersion',
    version: 'app.version.name',
    sdkName: 'sdk.name',
    sdkVersion: 'sdk.version',
    osName: 'os.name',
    osVersion: 'os.version',
    osVersionMajor: 'os.versionMajor',
    networkType: 'net.host.connection.type',
    deviceId: 'device.id',
    deviceScreen: 'device.screen',
    browser: 'browser',
    browserVersion: 'browser.version',
    browserVersionMajor: 'browser.versionMajor',
    webviewId: 'app.webviewId',
    orsSdkVersion: 'app.appSdkVersion',
    webviewStartTime: 'app.webviewStartTime',
    deviceModel: 'device.model.name',
    instanceId: 'view.instanceId',
    createTime: 'view.createTime',
    customTags: 'custom.tags',
    userAgent: 'userAgent',
  },
  resource: {
    rumType: 'rum.type',
    id: 'resource.id',
    type: 'resource.type',
    loadType: 'resource.loadType',
    protocol: 'resource.protocol',
    url: 'resource.url',
    host: 'resource.url.host',
    path: 'resource.url.path',
    query: 'resource.url.query',
    method: 'resource.method',
    status: 'resource.status',
    size: 'resource.size',
    transferSize: 'resource.receive.size',
    dns: 'resource.dns.duration',
    tcp: 'resource.tcp.duration',
    ssl: 'resource.ssl.duration',
    ttfb: 'resource.ttfb.duration',
    trans: 'resource.trans.duration', // 资源加载内容传输时间
    firstbyte: 'resource.firstbyte.duration', // 资源加载首包时间
    request: 'resource.send.duration',
    response: 'resource.receive.duration',
    redirect: 'resource.redirect.duration',
    body: 'resource.body', // api请求下有body
    // txid:'X-ORS-TxId', // header里的txid
    txid: 'resource.txid',
    cache: 'resource.cache.duration',
    netType: 'resource.netType',
    nextHopProtocol: 'resource.protocol.version',
    duration: 'resource.duration',
    resourceStartTime: 'resource.startTime',
    resourceEndTime: 'resource.endTime',
    scenes: 'resource.scenes',
    resourceTiming: 'resource.timing',
    ...sessionCommon,
    ...viewCommon,
    ...userCommon,
    ...actionCommon,
  },
  error: {
    id: 'error.id',
    rumType: 'rum.type',
    type: 'error.type',
    subtype: 'error.subtype',
    mechanism: 'error.mechanism',
    msg: 'error.message',
    source: 'error.source',
    errorObj: 'error.stack',
    catId: 'error.catId',
    componentName: 'comp.name',
    orsCompMark: 'comp.mark',
    resourceType: 'resource.type',
    resourceId: 'resource.id',
    resourceStatus: 'resource.status',
    resourceUrl: 'resource.url',
    resourcehost: 'resource.url.host',
    resourcePath: 'resource.url.path',
    resourceMethod: 'resource.method',
    reasonId: 'error.blankScreen.reasonId',
    scenes: 'error.scenes',
    filename: 'error.filename',
    ...sessionCommon,
    ...viewCommon,
    ...userCommon,
    ...actionCommon,
    ...scopeCommon,
  },
  view: {
    rumType: 'rum.type',
    FP: 'view.firstPaintTime',
    FCP: 'view.firstContentfulPaint',
    LCP: 'view.largestContentfulPaint',
    FID: 'view.firstInputDelay',
    CLS: 'view.cumulativeLayoutShift',
    INP: 'view.interactionToNextPain', //交互到下一次绘制的延迟
    TTFB: 'view.TimeToFirstByte',
    FMP: 'view.firstMeaningPaint', // 首次有效绘制
    lcpElement: 'view.lcp.element',
    lcpId: 'view.lcp.id',
    lcpUrl: 'view.lcp.url',
    lcpLoadTime: 'view.lcp.loadTime',
    lcpRenderTime: 'view.lcp.renderTime',
    lcpSize: 'view.lcp.size',
    clsSource: 'view.cls.source',
    inpEventType: 'view.inp.eventType',
    inpElement: 'view.inp.element',
    inpId: 'view.inp.id',
    inpClassName: 'view.inp.className',
    inpSrc: 'view.inp.src',
    inpTextSnippet: 'view.inp.textSnippet',
    spentDuration: 'view.spent.duration', // 页面停留时间
    navigationTiming: 'view.navigationTiming',
    perfromanceTiming: 'view.perfromanceTiming',
    perfromanceTimeOrigin: 'view.perfromanceTimeOrigin',
    ...sessionCommon,
    ...viewCommon,
    ...userCommon,
    ...actionCommon,
  },
  action: {
    rumType: 'rum.type',
    type: 'action.type',
    name: 'action.name',
    actionId: 'action.id',
    duration: 'action.duration',
    actionStartTime: 'action.start.time',
    actionEndTime: 'action.end.time',
    ...sessionCommon,
    ...viewCommon,
    ...userCommon,
  },
  longtask: {
    rumType: 'rum.type',
    duration: 'longtask.duration',
    id: 'longtask.id',
    loadProcess: 'longtask.loadProcess',
    attributes: 'longtask.attributes',
    longtaskStartTime: 'longtask.startTime',
    longtaskEndTime: 'longtask.endTime',
    name: 'longtask.name',
    message: 'longtask.message',
    ...sessionCommon,
    ...viewCommon,
    ...userCommon,
    ...actionCommon,
  },
  comp: {
    id: 'comp.eventId',
    rumType: 'rum.type',
    name: 'comp.name',
    mark: 'comp.mark',
    status: 'comp.status',
    compStartTime: 'comp.startTime',
    compEndTime: 'comp.endTime',
    ...sessionCommon,
    ...viewCommon,
    ...userCommon,
    ...actionCommon,
  },
  console: {
    rumType: 'rum.type',
    id: 'console.id',
    level: 'console.level',
    args: 'console.args',
    startTime: 'console.startTime',
    endTime: 'console.endTime',
    ...sessionCommon,
    ...viewCommon,
    ...userCommon,
    ...actionCommon,
  },
};

export default aliasName;
